Stabilize Run_Miniconda.yml workflow

diff --git a/github_actions/Run_Miniconda.yml b/github_actions/Run_Miniconda.yml
--- a/github_actions/Run_Miniconda.yml
+++ b/github_actions/Run_Miniconda.yml
@@ -1,8 +1,6 @@
 name: Miniconda Environment
 
 on:
-  push:
-    - main
   workflow_dispatch:
 
 jobs:
@@ -16,10 +14,16 @@ jobs:
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
+      with:
+        path: ${{ github.workspace }}
+
+    - name: Check if Environment file exists
+      run: |
+        [ -f ${{ github.workspace }}/${{ env.CONDA_ENVIRONMENT_FILE }} ] || { echo "Error: ${{ env.CONDA_ENVIRONMENT_FILE }} file does not exist" >&2; exit 1; }
 
     - name: Install Miniconda
       run: |
-        apt-get update && apt-get install -y curl wget python3 python3-pip python3-venv
+        apt-get update && apt-get install -y wget
         mkdir -p ~/miniconda3
         wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
         bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
@@ -29,17 +33,22 @@ jobs:
       run: |
         echo "source ~/miniconda3/etc/profile.d/conda.sh" >> $GITHUB_PATH
         source ~/miniconda3/etc/profile.d/conda.sh
-        conda env create --file {{ env.CONDA_ENVIRONMENT_FILE }}
+        conda env create --file ${{ github.workspace }}/{{ env.CONDA_ENVIRONMENT_FILE }}
+
+    - name: Create a Python File For Testing
+      working-directory: ${{ github.workspace }}
+      run: |
+        echo "print('Hello World!')" > myscript.py
 
     - name: Run Python Script
       working-directory: ${{ github.workspace }}
-      continue-on-error: true
       run: |
         source ~/miniconda3/etc/profile.d/conda.sh
         conda activate {{ env.CONDA_ENVIRONMENT_NAME }}
         python myscript.py
 
-    - name: [Optional] Delete Messy Files
+    - name: Upload Repository [without cache files]
+      working-directory: ${{ github.workspace }}
       run: |
           find . -type d -name '.git' -exec rm -rf {} +
           find . -type d -name '.github' -exec rm -rf {} +
@@ -49,9 +58,12 @@ jobs:
           sudo rm -rf ./{{ env.CONDA_ENVIRONMENT_FILE }}
           find . -name '.DS_Store' -exec rm -rf {} +
           find . -type d -name 'venv' -exec rm -rf {} +
-          find . -type d -name '.pytest_cache' -exec rm -rf {} +          
+          find . -type d -name '.pytest_cache' -exec rm -rf {} +   
+          zip -r ${{ runner.temp }}/workspace-${{ github.sha }}.zip .
     - uses: actions/upload-artifact@v4
       with:
         name: workspace-${{ github.sha }}
         path: ${{ runner.temp }}/workspace-${{ github.sha }}.zip
         retention-days: 7
+        if-no-files-found: 'warn'
+        compression-level: 6
